// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://neamtpgdqbfuxotozkpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lYW10cGdkcWJmdXhvdG96a3BkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgyMzI0ODAsImV4cCI6MjA5MzgwODQ4MH0.jHLxo2-k6jHlf8_hOqbRXordMwuzqWiW0zPrAwhwZ2Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});